name: Notify Slack

inputs:
  success:
    description: Whether deployment succeeded or not
    type: boolean
    required: true
  bot_token:
    description: Slack bot token
    required: true
  environment:
    description: Which env was the app deployed to
    type: environment
    required: true
  version:
    description: The version of the deployed app
    required: false
  app_url:
    description: The URL where the app was deployed to
    required: false
  action_url:
    description: The URL GitHub Action for this build
    required: false
    default: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

runs:
  using: "composite"
  steps:
    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: C03ND2RUSTE
        payload: |
          {
            "text": "${{ inputs.environment }}: ${{ inputs.version }} ${{ inputs.app_url }} ${{ inputs.action_url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ inputs.success && :rocket: || ':skull_and_crossbones:' }} *${{ inputs.environment }}:* ${{ inputs.version }} <${{ inputs.app_url }}|:phone: App> <${{ inputs.app_url }}|:building_construction: Workflow>"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.bot_token }}