name: Deploy
on:
  push:
    branches:
      - alpha
      # - beta
      # - main

jobs:
  # TODO deployDev

  deployProd:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      # build
      - uses: ./.github/workflows/build.yml

      # deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BCSOL_A8522 }}"
          projectId: bcsol-a8522
          channelId: live